### ISSUE TITLE
MCA

### ISSUE THREAD

**Issue by Mattyice0207** [Catoshy/Improved-Vils#2]
MCA villagers Armor and weapons will disappear when being equipped

**Comment by Catoshy** [comment]
MCA villagers are changed in ways that this Mod cannot account for. MCA has it's own system for kitting out and arming the MCA villager entities which the MCA-Mod itself puts in the world. I have tested Improved-Vils on the vanilla villagers and it works fine. 

If you wish to have both vanilla and MCA villagers in your world, there is a setting in the configs for the MCA-Mod which handles with that. I may eke-in a setting in the Improved-Vils configs that will make the Mod deal _only_ with vanilla MC villagers and with it ward off players from losing things and other mischeif when trying to kit out entities from other Mods.
